server:
  port: 9090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: school-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/school/**
        
        